name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Write properties to file
      run: ls
    - name: Set up JDK 17
      uses: actions/setup-java@v3.10.0
      with:
        java-version: '17'
        distribution: 'adopt'


    - name: Checkout code
      uses: actions/checkout@v2
  


    - name: Run tests
      run: mvn test --file pom.xml
