name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Write properties to file
      run: |
        ls
        echo "spring.data.mongodb.uri=${{ secrets.URI }}" >> "AuthenticationService/src/main/resources/application.properties"
        echo "spring.data.mongodb.username=${{ secrets.USRANDPASS }}" >> "AuthenticationService/src/main/resources/application.properties"
        echo "spring.data.mongodb.password=${{ secrets.USRANDPASS }}" >> "AuthenticationService/src/main/resources/application.properties"
        echo "spring.data.mongodb.database=${{ secrets.DB }}" >> "AuthenticationService/src/main/resources/application.properties"
        echo "jwt.secret=${{ secrets.JWT_SECRET }}" >> "AuthenticationService/src/main/resources/application.properties"
    - name: Set up JDK 17
      uses: actions/setup-java@v3.10.0
      with:
        java-version: '17'
        distribution: 'adopt'


    - name: Checkout code
      uses: actions/checkout@v2
  


    - name: Run tests
      run: mvn test --file pom.xml
